name: ci/cd pipeline to deploy to tomcat
on: 
  push:
    branches: 
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Validate with Maven
        run: mvn validate

      - name: Compile with Maven
        run: mvn compile
      
      - name: Test with Maven
        run: mvn test
      
      - name: Package with Maven
        run: mvn clean package

      - name: Verify WAR file
        run: ls -lh target/

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/*.war

  deploy-dev:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file

      - name: Deploy to DEV Tomcat
        env:
          URL: ${{ secrets.TOMCAT_HOST }}
          USER: ${{ secrets.TOMCAT_USER }}
          PASS: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          WAR_FILE=$(ls *.war | head -n 1)
          echo "Deploying $WAR_FILE to DEV ($URL)"

          curl -v -u "$USER:$PASS" --fail --show-error -T "$WAR_FILE" \
          "$URL/deploy?path=/train-ticket-reservation&update=true"
